### ISSUE TITLE
Working with 2.0

### ISSUE THREAD

**Issue by chadams** [MichaelSolati/geofirestore#14]
I'm trying to use version 2.0.0, but it doesn't have a "dist" folder and is therefore giving the error (Cannot find module 'geofirestore')

I don't think I can use 1.2.0 right now because it looks like it doesn't support adding additional fields to the collection (which I need)

anyway to build and publish 2.0?

**Comment by MichaelSolati** [comment]
What's the exact version of v2.0 are you using?? (From your package.json). Cause I know other ppl have used it just fine, so I wanna make sure this is isolated, and can be resolved.

(P.S., just to clarify some bits, you can build v2 with the `npm run build` command, you can also install a version 2 beta with `npm i geofirestore@next`)

**Comment by chadams** [comment]
thanks, had the wrong version installed
